### PR TITLE
feat: [NO-JIRA] - Bump Pydantic version from 1.X to 2.X

### PR DESCRIPTION
**Pull request by afranzi**
This PR aims to upgrade elementary to start using Pydantic 2.0

Changes done:
- Upgrade the Pydantic major version.
- Update `validator` for `field_validator` due to deprecation.

### CODE REVIEW

**Comment by NoyaArie** [comment]
Hey @afranzi thank you for submitting this PR!

The code quality and tests are failing. 

Could you please install the packages from the `dev.requirements.txt` After that run the pre-commit and the tests:
1. pre-commit install
2. pre-commit run --all-files --verbose
3. pytest

🙏

**Comment by elongl** [comment]
Closing as unplanned for now.
Would love to understand the motivation for this a bit better.

**Comment by afranzi** [comment]
Hello, any update on this request? it would be good to support the new pydantic version as I believe companies are moving ahead with the Pydantic 2.X version.

**Comment by ellakz** [comment]
Hi, closing this PR as I had merged a different solution supporting both pydantic 1 and 2, should be available in our next release 0.14.1

**Pull request closed without merging**
