### PR TITLE
Loosen the version constrain of the click package

### PR DESCRIPTION
**Pull request by yu-iskw**
## Motivation
I got the error message to install elementary in addition to dbt-core. I assume that is caused by the difference of the version constrains of the click package in dbt-core and elememtary. I would expect pip appropriately handle the version constrains in both of dbt-core and elementary. But, sometimes it doesn't work. In my opinion, we are probably loosen the version constrains so that we can also catch up with new releases of click. The latest version is today 8.1.7.

- pip: 23.3.2
- dbt-core: 1.7.11

```shell
$ pip install 'elementary-data[bigquery]'
...
elementary-data 0.14.0 requires click<8.1.4,>=7.0, but you'll have click 8.1.7 which is incompatible.
```

https://github.com/dbt-labs/dbt-core/blob/c86cec3256cfeb636d47f21279f3cb689d585439/core/setup.py#L62

### CODE REVIEW

**Comment by yu-iskw** [comment]
@oravi Sorry for bothering your. What are your thoughts on the change?

**Comment by mi-volodin** [comment]
Upvoting this one. 
Elementary-data now in direct conflict with Airflow 2.7.2 [constraints](https://github.com/apache/airflow/blob/1416d3662da4e61e5b9b72accc5bd3c21e042368/constraints-3.8.txt#L256) where click has == 8.1.7 version.

List of changes [for the click](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-7) since 8.1.4, seems only issue fixes and no breaking changes.

**Comment by mi-volodin** [comment]
@haritamar Can you take a look at this? I saw you closed a[ pydantic issue,](https://github.com/elementary-data/elementary/issues/1421) which is similar (I wonder how it wasn't mentioned in the same issue).

**Review by haritamar — APPROVED** [review]

**Comment by haritamar** [comment]
Hi @mi-volodin  and @yu-iskw !
Sorry for the delay here.
The limitation was meant to be temporary due to an issue in v8.1.4 specifically - but we can totally loosen it now.

**Comment by mi-volodin** [comment]
@haritamar thanks a lot! A great relief for the team.
@yu-iskw thanks for making a PR 🙏

**Comment by yu-iskw** [comment]
@haritamar Thank you for merging this.

**Comment by yu-iskw** [comment]
@haritamar Can we release a new version which includes the changes?

**Pull request merged**
